[package]
name = "shaded-flowers-ld-52"
version = "0.1.0"
edition = "2021"

[dependencies]
geng = "0.14.0"
serde = "1"
resvg = "0.28.0"
usvg = "0.28.0"
tiny-skia = "0.8.2"
notify = "4.0.17" # File watch
regex = "1.5.6"
chrono = "0.4"
tween = "2.0.0"
strfmt = "0.2.2"
enum-utils = "0.1.2"  # sudo port install x86_64-w64-mingw32-gcc

[patch.crates-io]
# Temp workaround until update in geng, as this issue is already fixed upstream
# https://github.com/jdm/tinyfiledialogs-rs/issues/36
tinyfiledialogs = { git = "https://github.com/kuviman/tinyfiledialogs-rs", branch = "fix-cross" }
geng = { git = "https://github.com/kuviman/geng", branch = "main" }
